Makefile
cmd/bolt/main.go
db_test.go
freelist.go

Fix https://github.com/coreos/bbolt/issues/2.

gofmt, change git path

---

db_test.go

fixes https://github.com/boltdb/bolt/issues/645

fix overflow breaking 32-bit test builds

---

bolt_mips64x.go
bolt_mipsx.go

via https://github.com/boltdb/bolt/pull/663

Add support for mips, mips64

---

Makefile
bucket.go
cmd/bolt/main.go
db.go
db_test.go
freelist.go
tx.go

add unused, gosimple, gofmt to the makefile
unused fails on defaultPageSize which is used in the PageSize branch

more fmt passes

---

db.go

via https://github.com/boltdb/bolt/pull/410

do not read freelist if database opened readonly

---

bucket_test.go
db.go
db_test.go

Options.PageSize

---

cmd/bolt/main.go
cmd/bolt/main_test.go

Looks reasonable.
via https://github.com/boltdb/bolt/pull/402

Add "buckets", "keys" and "get" CLI commands

---

README.md

README: explain purpose of bbolt fork

---

Makefile
README.md

add coverage reports

---

db_test.go

Was filling up all the disk space in Jenkins VMs.
And some var assign nits.

db_test.go: remove temp files after tests

---

tx.go

https://github.com/boltdb/bolt/commit/fa91bb2ff81dfc60822bf451c515f389b1d608cd

Cherry-pick "add tx-copy-deprecated"

---

README.md

- Update README to add reef-pi to project list

Add reef-pi to the list of projects that use Bolt 

---

README.md

- The list of project use bolt sorted by initials
- Format "Table of Contents"

The list of project use bolt sorted by initials

---

README.md

Suggesting the addition of a query language and library I worked on for use with the original Bolt DB, Updated for bbolt. Thanks for keeping the bolt project going! :+1:

Add kval-access-language to README.md

---

.gitignore
allocate_test.go
freelist.go
freelist_test.go

update: use the `readIDs` to init the freelist ids and update the .gitignore to igore go test cover.out

update the freelist readIDs

---

db.go
freelist.go
freelist_test.go

add getFreePageIDs

---

bolt_riscv64.go

Add support for riscv64 arch.

---

bolt_riscv64.go

Fix the build on Go 1.10 and before

---

cmd/bbolt/main.go
cursor.go
freelist_hmap.go

No need to convert here, they are already of the right type.

Avoid unnecessary conversions

---

README.md

there is not a method for DB called CreateBucket()

DB.CreateBucket() -> Tx.CreateBucket()

---

simulation_test.go

This PR fixes a test in `simulation_test.go` where some of the error conditions could never be recorded, because they were happening inside a goroutine.
`T.Fatal()` is a convenience function that combines `T.Log()` and `T.FailNow()`. 
From the godoc of `T.FailNow()`: 
> FailNow must be called from the goroutine running the test or benchmark function, not from other goroutines created during the test. Calling FailNow does not stop those other goroutines.
To see this in action, take a look at `main_test.go` in my [example repo](https://github.com/alrs/fatalfail/).

Fix Swallowed goroutine Error Statements

---

bucket.go

Simple grammar fix

---

db_test.go

Fixes #165 
I used to have a PR for 5 test functions (#186), but it seems that you have already fixed 1 of these test functions recently, and I messed up with the commits, so I opened a new PR for 4 test functions.
***Description***
In 4 test functions, `t.Fatal()` is called in child goroutines, instead of in the test goroutine. This is a common misusage of `t.Fatal()`, because `t.Fatal()` calls `t.FailNow()`:
[FailNow must be called from the goroutine running the test or benchmark function, not from other goroutines created during the test. Calling FailNow does not stop those other goroutines.](https://golang.org/pkg/testing/#B.FailNow)
***How they are fixed***
A channel is used to receive error. This channel has buffer to guarantee the send won't block. I mimicked your recent usage for …

Fix the misusage of t.Fatal() in 4 test functions

---

bolt_arm.go

cc #201 https://github.com/etcd-io/bbolt/pull/201/files#r395260497 @jrick

Remove unused import to fix arm builds

---

.gitignore
.travis.yml
cmd/bbolt/main.go
compact.go

fix etcd-io/bbolt#247 move compact logic

---

tx.go

Use WriteTo() instead

---

db.go

Simplified code

---

.gitignore

Signed-off-by: Huahang Liu (Hans) <hliu@me.com>

ignore goland ide generated files

---

Makefile
db_test.go
tx_test.go

Signed-off-by: JmPotato <ghzpotato@gmail.com>

Clean and simplify some code

---

bolt_loong64.go

This commit is adding support for LoongArch architecture.

Add support for loong64 arch.

---

cmd/bbolt/main.go

add possibility to gain keys and values for sub buckets.

sub buckets in get+keys cmd

---

.github/workflows/tests.yaml
cmd/bbolt/main.go
compact.go
db_test.go
tx.go
tx_test.go
unix_test.go

Attempt to fix the rest of the linting issues, mostly error handling.

Enable lint in github actions

---

CHANGELOG.md

Added a changelog file for 1.3.x, and planning to release 1.3.7 with a detailed changelog for users reference.
cc @ptabor @serathius @spzala

add changelog for boltDB

---

bucket.go

Small improvements

---

cursor.go

only perform assert check on exported method

---

.github/workflows/tests.yaml
Makefile
db.go

Fix https://github.com/etcd-io/bbolt/issues/364

Support running workflow on Windows-latest

---

.gitignore

add /cmd/bbolt/bbolt into .gitignore

---

cmd/bbolt/main.go
cmd/bbolt/page_command.go

move all common fields into baseCommand

---

cmd/bbolt/surgery_commands.go
cmd/bbolt/surgery_commands_test.go

Linked to https://github.com/etcd-io/bbolt/issues/370
This PR is on top of https://github.com/etcd-io/bbolt/pull/386.

Add `bbolt surgery copy-page` command

---

cmd/bbolt/main.go

Add support for using sha256 sum for obfuscating values

---

cmd/bbolt/surgery_commands.go

Extracted from https://github.com/etcd-io/bbolt/pull/408. It should can be reviewed & merged separately.
Previously we added command `surgery clear-page`, but did not update the command usage.

Update the usage of surgery command

---

cmd/bbolt/main.go

Fix redacted format

---

bucket.go
cursor.go
freelist.go
internal/common/page.go
node.go
tx.go
tx_check.go

Adding methods to check the page type.

Encapsulate the logic of checking the page type

---

cmd/bbolt/main.go

display progress during benchmark

---

cmd/bbolt/main.go
tx_check.go

Resolve https://github.com/etcd-io/bbolt/pull/395#discussion_r1136612538

bbolt: remove `CheckWithOptions` and add variadic parameter options to method `Check`

---

node.go

Resurrected #256 (rebased over master)

Merge redundant codes in node.rebalance

---

db.go

Fix review comment in https://github.com/etcd-io/bbolt/pull/433#discussion_r1146001577

update the error message when rollback unmap also fails

---

db_test.go

fix https://github.com/etcd-io/bbolt/issues/441

test: improve testDB_Close_PendingTx to reduce flaky

---

cmd/bbolt/command_surgery_cobra.go
cmd/bbolt/command_surgery_cobra_test.go
internal/surgeon/surgeon.go

Fix comment https://github.com/etcd-io/bbolt/pull/417#discussion_r1148159676
Linked to https://github.com/etcd-io/bbolt/issues/370

cmd: add `surgery abandon-freelist` command

---

concurrent_test.go
go.mod
go.sum

Linked to https://github.com/etcd-io/bbolt/issues/369
More test cases will be added in separate PR.

test: add test case to verify concurrent reading and writing transactions always work correctly

---

db.go
freelist.go
freelist_test.go
internal/btesting/btesting.go
internal/common/types.go

Followup to https://github.com/etcd-io/bbolt/pull/459

Move FreelistType from `internal/common` to top level package `bbolt`

---

concurrent_test.go

follow up to https://github.com/etcd-io/bbolt/pull/455#discussion_r1166542936

test: get all concurrent test parameters wrapped in a struct

---

cmd/bbolt/command_surgery_cobra.go
cmd/bbolt/command_surgery_cobra_test.go

See https://github.com/etcd-io/bbolt/issues/370#issuecomment-1491075075

cmd: add 'surgery freelist rebuild' command

---

concurrent_test.go

followup to https://github.com/etcd-io/bbolt/pull/455#discussion_r1166473894

test: verify that txids are incremental

---

README.md

fix https://github.com/etcd-io/bbolt/issues/448
Please anyone feel free to integrate with Codecov in a separate PR. 
also removed the build badge.

Remove codecov and build badges

---

concurrent_test.go

followup to https://github.com/etcd-io/bbolt/pull/469#discussion_r1175113338

test: rename runOperation to executeOperation

---

concurrent_test.go

ensure the db file is saved in case of panicking.

test: save data in deferred function

---

concurrent_test.go

test: check database consistency at the end of concurrent test case

---

concurrent_test.go

The purpose is to ensure the test case can be executed on old branch or version, e.g. release-1.3 or 1.3.[5-7].

test: update concurrent test case to remove the dependency on internal package

---

cmd/bbolt/command_surgery_cobra.go
cmd/bbolt/command_surgery_cobra_test.go
cmd/bbolt/surgery_commands.go
cmd/bbolt/surgery_commands_test.go

Linked to https://github.com/etcd-io/bbolt/issues/472

Migrate `surgery revert-meta-page` to cobra style command

---

db.go
tests/failpoint/db_failpoint_test.go

cc @mitake @ptabor @serathius @spzala

add failpoint 'resizeFileError' to simulate file.Truncate error

---

cmd/bbolt/command_surgery_cobra.go

Decompose command options

---

README.md

Add bucket retrieve example to README

---

tx.go

Update Tx.Commit documentation

---

db.go
db_test.go

Do not create db file if opened read-only

---

concurrent_test.go

When committing a write transaction, bbolt will not release pages which are accessible to the running read transactions. Instead, bbolt puts the pages into a pending list, and dot not release them until the related read transaction finishes.
This test case intentionally creates the scenario that read and write transactions are interleaved.

test: add test case to verify repeatable read

---

node.go

Adjust rebalance threshold with Bucket.FillPercent

---

.github/workflows/failpoint_test.yaml
.github/workflows/tests.yaml

This PR update go version to 1.19.10
/cc @jmhbnz

update go to latest patch release 1.19.10

---

bucket.go

Update Bucket.Get documentation

---

errors.go
errors/errors.go

delete unnecessary error info

---

CHANGELOG/CHANGELOG-1.3.md

For https://github.com/etcd-io/bbolt/issues/542

Add changelog items for 1.3.8

---

CHANGELOG/CHANGELOG-1.3.md

Update changelog format error

---

concurrent_test.go
go.mod
go.sum

Fix issue https://github.com/etcd-io/bbolt/issues/599
Add's concurrent_test.go in master branch to release-1.3 branch.

Backport concurrent_test.go to release-1.3 branch

---

.github/workflows/tests-template.yml

Add metrics collection step to GitHub actions. Part of etcd-io/etcd#17045.

github actions: add workflow telemetry to collect metrics

---

tx_check.go

Linked to https://github.com/etcd-io/bbolt/issues/580
The purposes:
- to make the common method to be reused by following PR
- to make the reviewing on the following PR as easy as possible

Move checking the invariant properties into a common method

---

version/version.go

Link to https://github.com/etcd-io/bbolt/issues/553

Update bbolt version to 1.4.0-alpha.0

---

CHANGELOG/CHANGELOG-1.3.md

Linked to https://github.com/etcd-io/bbolt/pull/683 and https://github.com/etcd-io/bbolt/issues/681

Add changelog item for release-1.3 to cover the fix for bbolt keys and get commands

---

OWNERS

Update ahrtr's email

---

OWNERS

cc @ptabor @serathius @spzala 
Link to https://github.com/etcd-io/etcd/pull/17385

Remove mitake from OWNERS

---

CHANGELOG/CHANGELOG-1.3.md

Link to https://github.com/etcd-io/bbolt/issues/696

Update the release date of v1.3.9

---

tx_check.go
tx_check_test.go

Address: https://github.com/etcd-io/bbolt/pull/698#discussion_r1501818465

Change the type of pageId uint -> uint64.

---

errors.go
errors/errors.go

Signed-off-by: Park Zhou <ideapark@139.com>

all: fix doc of var ErrChecksum

---

cmd/bbolt/main_test.go

Discussion: https://github.com/etcd-io/bbolt/pull/713#discussion_r1552320406

Remove unused seed generation code

---

.github/workflows/stale.yaml

Add workflow to close stale issues and PRs

---

README.md
cmd/bbolt/command_surgery.go
cmd/bbolt/main.go
db.go

use errors.New to replace fmt.Errorf with no parameters will much better

chore: use errors.New to replace fmt.Errorf with no parameters will much better

---

README.md

Followup of https://github.com/etcd-io/bbolt/pull/734
Link to https://github.com/etcd-io/bbolt/issues/733
cc @Elbehery @ivanvc @fuweid @tjungblu

Update readme to clearly clarify the behaviour of Next and Prev

---

CHANGELOG/CHANGELOG-1.3.md

Link to https://github.com/etcd-io/bbolt/issues/746
cc @Elbehery @fuweid @ivanvc @tjungblu

Update changelog for 1.3.10

---

cmd/bbolt/main.go

This replicates the output of testing.B, so it can be used with other tools. Example output:
```
bench -count 100000 -batch-size 25000 -profile-mode w -gobench-output
starting write benchmark.
Starting write iteration 0
Finished write iteration 0
Starting write iteration 25000
Finished write iteration 25000
Starting write iteration 50000
Finished write iteration 50000
Starting write iteration 75000
Finished write iteration 75000
starting read benchmark.
Write     100000               730.0 ns/op
Read    104900000                9.534 ns/op
```
The alignment is a bit annoying, but the format specification just says there must be spaces between.

add gobench output option

---

db_test.go

Enhance `TestDB_Concurrent_WriteTo` to verify that all readonly transactions, which are created based on the same data view, should always read the same data.

Enhance `TestDB_Concurrent_WriteTo` to check consistent read

---

CHANGELOG/CHANGELOG-1.3.md

cc @fuweid @tjungblu @ivanvc @Elbehery 
prepare for the release of 1.3.11

Add changelog for 1.3.11

---

CHANGELOG/CHANGELOG-1.3.md

https://github.com/etcd-io/bbolt/releases/tag/v1.3.11
cc @fuweid @ivanvc @tjungblu @Elbehery

Update release date of 1.3.11

---

cursor_test.go

docs: remove repetitive words

---

CHANGELOG/CHANGELOG-1.4.md

cc @fuweid @ivanvc @serathius @jmhbnz

Update changelog for v1.4.0

---

.github/workflows/tests-template.yml

ref https://github.com/etcd-io/etcd/issues/19417

bump golangci-lint v1.64.5

---

bolt_windows.go
db.go
db_test.go
errors/errors.go
internal/btesting/btesting.go

add support for data file size limit

---

.golangci.yaml
cmd/bbolt/main.go
internal/common/page.go
tests/robustness/powerfailure_test.go
tx_check.go

This PR replaces https://github.com/etcd-io/bbolt/pull/958
Author is @mmorel-35 
cc @ivanvc

fix staticcheck issues

---

db.go

This reverts https://github.com/etcd-io/bbolt/pull/969 
addresses comment https://github.com/etcd-io/bbolt/pull/969#issuecomment-2956621104
cc @ahrtr @ivanvc

[release-1.4] Revert "Merge pull request #969 from nspcc-dev/drop-unused-txs"

---

bolt_aix.go
bolt_android.go
bolt_solaris.go

Backport https://github.com/etcd-io/bbolt/pull/988 to 1.4.
cc @Elbehery @fuweid @ivanvc  @tjungblu

[release-1.4] Fix maxMapSize typo in aix, android and solaris

---

tx.go

Backport both https://github.com/etcd-io/bbolt/pull/989 to 1.4

[release-1.4] Protect meta page when it's being written

---

tx.go

Backport both https://github.com/etcd-io/bbolt/pull/989 to 1.3

[release-1.3] Protect meta page when it's being written

---

CHANGELOG/CHANGELOG-1.4.md

cc @Elbehery @fuweid @ivanvc @jmhbnz  @tjungblu

Update v1.4.2's release date

---

scripts/release.sh

See https://github.com/etcd-io/bbolt/issues/996#issuecomment-3012584780 
cc @ahrtr @ivanvc

chore(release): fix release script for MacOS

---

cmd/bbolt/command_info.go
cmd/bbolt/command_info_test.go
cmd/bbolt/command_root.go
cmd/bbolt/main.go
cmd/bbolt/main_test.go

part of https://github.com/etcd-io/bbolt/issues/472

chore(cmd): migrate `info` command to cobra style

---

cmd/bbolt/command_pages.go
cmd/bbolt/command_pages_test.go
cmd/bbolt/command_root.go
cmd/bbolt/main.go
cmd/bbolt/main_test.go

part of https://github.com/etcd-io/bbolt/issues/472

chore(cmd): migrate `pages` command to cobra style

---

cmd/bbolt/command_keys.go
cmd/bbolt/command_keys_test.go
cmd/bbolt/command_root.go
cmd/bbolt/main.go
cmd/bbolt/main_test.go

part of https://github.com/etcd-io/bbolt/issues/472

chore(cmd): migrate `keys` command to cobra style

---

cmd/bbolt/command_page_item.go
cmd/bbolt/command_page_item_test.go
cmd/bbolt/command_root.go
cmd/bbolt/main.go
cmd/bbolt/main_test.go

cmd: migrate `page-item` command to cobra style

---

cmd/bbolt/main.go

fix first part of https://github.com/issues/assigned?issue=etcd-io%7Cbbolt%7C975
sequential write with delete.
Every tx deletes a fraction of keys inserted by previous tx.
the fraction is 0.1.

add write mode "seq-del"

---

.github/workflows/tests_windows.yml

See https://github.com/etcd-io/bbolt/pull/1028#issuecomment-3092381430
cc @ahrtr @ivanvc

chore(test): bump_windows_test_timeout

---

cmd/bbolt/command_page.go
cmd/bbolt/command_page_test.go
cmd/bbolt/main.go

See https://github.com/etcd-io/bbolt/pull/1029#discussion_r2212764548

chore(cmd): add exclusive behaviour to page cmd

---

db_test.go

Fix https://github.com/etcd-io/bbolt/issues/1044

Fix test case TestDB_HugeValue for 32 bit systems

---

db_test.go
tx.go

cc @fuweid @Elbehery @ivanvc @tjungblu

Update (*Tx)WriteTo to reuse the already opened file if WriteFlag not set

---

db_test.go
tx.go

Backport https://github.com/etcd-io/bbolt/pull/1057 to 1.3
cc @Elbehery @fuweid @ivanvc @tjungblu

[release-1.3] Update (*Tx)WriteTo to reuse the already opened file if WriteFlag not set

---

CHANGELOG/CHANGELOG-1.3.md
CHANGELOG/CHANGELOG-1.4.md

@Elbehery @fuweid @ivanvc @tjungblu

Update release date for 1.3.12 and 1.4.3

---

tx.go

[release-1.4] fix a typo

---

cmd/bbolt/command/command_get.go
cmd/bbolt/command/errors.go

Found some typos in the last migrated cli code, thought to fix them :) 
cc @ivanvc @ahrtr

chore: fix some cli typos
